FROM node:24-alpine AS build

WORKDIR /app

ARG VITE_NET_API_URL=http://localhost:3000/api/v1
ARG VITE_NET_API_TOKEN=
ARG VITE_NET_VERSION=0.2.0-dev.0
ARG VITE_NET_COMMIT_SHA=development
ARG VITE_NET_BUILD_TIME=unknown
ARG VITE_NET_IMAGE_REF=local
ENV VITE_NET_API_URL=$VITE_NET_API_URL
ENV VITE_NET_API_TOKEN=$VITE_NET_API_TOKEN
ENV VITE_NET_VERSION=$VITE_NET_VERSION
ENV VITE_NET_COMMIT_SHA=$VITE_NET_COMMIT_SHA
ENV VITE_NET_BUILD_TIME=$VITE_NET_BUILD_TIME
ENV VITE_NET_IMAGE_REF=$VITE_NET_IMAGE_REF

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
